name: Playwright Cucumber Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # Chỉ chạy nếu dùng TypeScript và có script build
      # - name: Build TypeScript files
      #   run: npm run build # hoặc tsc

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Cucumber tests
        run: npm run test
        # hoặc npx cucumber-js nếu không có script

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/